# Generated by Django 4.2.13 on 2024-07-18 08:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('bra_image', models.ImageField(blank=True, null=True, upload_to='brand')),
                ('featured', models.BooleanField(default=False)),
                ('popular', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '2. Brands',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='category')),
                ('featured', models.BooleanField(default=False)),
                ('popular', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category')),
            ],
            options={
                'verbose_name_plural': '1. Categories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('old_price', models.PositiveIntegerField(default=0)),
                ('in_stock_total', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(default='N/A')),
                ('additiona_des', models.TextField(default='N/A')),
                ('shipping_return', models.TextField(default='N/A')),
                ('featured', models.BooleanField(default=False)),
                ('trending', models.BooleanField(default=False)),
                ('top_deals', models.BooleanField(default=False)),
                ('popular', models.BooleanField(default=False)),
                ('new_arrivals', models.BooleanField(default=False)),
                ('recommendation', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bra_products', to='store.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_products', to='store.category')),
            ],
            options={
                'verbose_name_plural': '3. Products',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Variations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variation', models.CharField(choices=[('color', 'color'), ('size', 'size'), ('none', 'none')], default='none', max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('variation_image', models.ImageField(blank=True, null=True, upload_to='variaton')),
                ('price', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
            options={
                'verbose_name_plural': '5. Variations',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gallery', models.ImageField(blank=True, null=True, upload_to='product')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_images', to='store.product')),
            ],
            options={
                'verbose_name_plural': '4. Products Images',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DealsOutlet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('pragh', models.CharField(blank=True, max_length=150, null=True)),
                ('limit', models.PositiveIntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals_outlet', to='store.product')),
            ],
            options={
                'verbose_name_plural': '7. Deals & Outlet',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BannerOverlay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('off', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_overlay', to='store.product')),
            ],
            options={
                'verbose_name_plural': '6. BannerOverlay',
                'ordering': ['-id'],
            },
        ),
    ]
