# Generated by Django 4.2.13 on 2024-07-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='color_varinat',
            new_name='color_variant',
        ),
    ]
